Subscription plans pricing card alignment completed
NatalNineITSolutions/cloud-storage pull request #1
Opened 2024-08-21 14:16 UTC by Janarthanan1999

Description:
Made Subscription plan card alignment and subscription radiobutton alignment completed.
CheckList:
Do the PR <= 10 files touched? - YES
Are the total lines of code changes in the 100-150 lines of code? - YES
Have you ensured proper linting was applied to your code? - YES
Have you checked to see if your code looks organized and easy to understand? - YES
Have you added comments to the PR? - YES
Have you added the ticket link to the PR? - YES
Have you added a short description of how you have implemented the changes and included the link for the analysis document? -YES
Have you added proof of testing to your PR - YES
Have you made sure Build is passing in CI/CD when you raise the PR? -YES
Ticket Link -[  CS-0 Project Setup and Create Subscription for Team (Subscription Plan alignment completed)](https://beta.zeedone.com/task/0822a2e3f6c396234216ac0d9d3bc44b?expires=1724854092&signature=6137037e86664f67dc791130dcb91184f0b743745f13d9735a34eea5bb968681)
Testing Proof:
There is alignment have only 3 cards in a row but now i worked in UI part and changed to 4 Cards.

![Screenshot 2024-08-21 194337](https://github.com/user-attachments/assets/11dd1149-8be7-47c2-a23a-600223fef42e)

2024-08-21 17:17 UTC, NatalNineITSolutions requested changes
@Janarthanan1999 The code needs proper linting. Currently, the code doesn't have linting.

2024-08-22 05:18 UTC, Dinesh-natalnine commented
Don not add inline style css only use Tailwind CSS in ClassName in the project

2024-08-22 05:37 UTC, NatalNineITSolutions approved these changes

2024-08-22 05:43 UTC, Dinesh-natalnine approved these changes
I can approve this. The alignment of the subscription plans pricing cards looks good now.

2024-08-22 05:44 UTC, merged